sudo: required
services:
  - docker

before_install:
  - docker build -t atr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true atr/docker-react npm run test # FOR TESTS

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elastikbeanstalk-us-west-2-id..."
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"