version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5003:3000"
    volumes:
      - /app/node_modiles
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
      volumes:
        - /app/node_modiles
        - .:/app
      command: ["npm", "run", "test"]

